### ISSUE TITLE
Create repository hosting guidelines

### ISSUE THREAD

**Issue by Arturas-K** [Callcredit/Policies#2]
We need to have a set of guidelines for repositories that we going to host under Callcredit organisations.
Guidelines should cover these questions:
 * what repos are good candidates?
 * what repos are not allowed?
 * how maintainers should be organised?
 * what is our minimum commitment for maintaining hosted repos?
 * what should be included in each repo (readme.md, code of conduct, licence etc)?

**Comment by Arturas-K** [comment]
@ColinM9991 @Edgixshua @sqldan please have a look

**Comment by ColinM9991** [comment]
I'm also interested in this and it may be good to have a group chat during the week.

We're currently working on a Problem+Json package for ASP.NET Core which provides an implementation for the Problem+Json standard in C# and is definitely a good candidate for open sourcing as it is not a company-specific implementation, but the question is what level of commitment will we have following the open sourcing of this. Particularly how we have separation between our current approach for work items and stories on our backlog with open-source repositories.

**Comment by Edgixshua** [comment]
I think we also need to take into account people's profiles. If you make your organisation information public then you need to bear in mind that for every contribution you make to any project, people can see that you are affiliated with Callcredit (I have mine set to private so people can't see what organisations I'm a member).

**Comment by Arturas-K** [comment]
This is covered by code of conduct scope part. When you are part of Callcredit organisation you must comply with code of conduct.
Also i want to have Organisation visible on people's profiles as this will promote Callcredit name.

Arturas

________________________________

**Comment by sqldan** [comment]
Agreed. And if you don't want to link CallCredit to your own profile, you can create a new profile to provide that separation. 

How do we define what we consider to be intellectual property, and what we want to share. What about licencing? https://opensource.org/licenses

**Comment by sqldan** [comment]
Ah, just saw the licencing issue :D

**Comment by Arturas-K** [comment]
will have to hold this one.
Same as #3, we are not going to allow hosting repos for now.
