### ISSUE TITLE
Agree what open source licence our hosted repos should include

### ISSUE THREAD

**Issue by Arturas-K** [Callcredit/Policies#3]
Agree on a standard licence approach for all hosted repositories.
Here are most popular open source licenses: https://opensource.org/licenses

Microsoft is mostly publishing under [MIT licence](https://opensource.org/licenses/MIT) should we do the same?

Chosen licence should be added to this repo.

**Comment by Arturas-K** [comment]
@ColinM9991 @Edgixshua @sqldan please have a look

**Comment by sqldan** [comment]
I like the MIT one. To the point. Maybe we'll want to change at some point, but this looks like a good one to start with. Plus, if it's good enough for Microsoft.

**Comment by Arturas-K** [comment]
Will have to hold this one.
As for first phase we are not going to host repos.
