### ISSUE TITLE
Define code of conduct

### ISSUE THREAD

**Issue by Arturas-K** [Callcredit/Policies#4]
Agree on Callcredit code of conduct.
We can use template from: 
 * https://contributor-covenant.org/
 * http://todogroup.org/opencodeofconduct/

or maybe take Microsoft one as template which is combination of the two:
https://opensource.microsoft.com/codeofconduct/

**Comment by sqldan** [comment]
Again, I'm happy with the Microsoft one.

**Comment by Arturas-K** [comment]
I have added another version of code of conduct this one is based on MS one.
PR #1 - Contribution Covenant version
PR #7 - MS and Contribution Covenant adapted

Vote witch one you prefer

**Comment by DannyArr** [comment]
I prefer number 7. I especially like the part that states, "We expect the code to be followed in spirit as much as in the letter." Typo in the Attribution section though. :)

**Comment by thelethalkind** [comment]
:+1: #7

**Comment by Arturas-K** [comment]
closed by #7
